const STORAGE = "aiLifeAdmin_v4";
const SESSION = "aiLifeAdminSession_v4";
const THEME = "aiLifeAdminTheme_v4";

const emptyData = () => ({
  tasks: [],
  notes: [],
  goals: [],
  bills: [],
  documents: [],
  expenses: [],
  income: [],
  habits: [],
  health: {water:0,waterTarget:8,sleep:0,sleepTarget:8,steps:0,stepTarget:8000,mood:"—",appointments:0},
  events: []
});

let data = emptyData();
let session = null;

const app = document.getElementById("appContent");
const title = document.getElementById("pageTitle");
const toast = document.getElementById("toast");
const backdrop = document.getElementById("modalBackdrop");
const modal = document.getElementById("modal");

const esc = s => String(s ?? "").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const uid = () => Date.now().toString(36)+Math.random().toString(36).slice(2,7);
function notify(msg){toast.textContent=msg;toast.classList.add("show");clearTimeout(notify.t);notify.t=setTimeout(()=>toast.classList.remove("show"),2400)}
function save(){if(session){localStorage.setItem(STORAGE+"_"+session.email,JSON.stringify(data))}}
function load(){if(session){try{data=JSON.parse(localStorage.getItem(STORAGE+"_"+session.email))||emptyData()}catch{data=emptyData()}}}
function openModal(html){modal.innerHTML=html;backdrop.classList.add("show")}
function closeModal(){backdrop.classList.remove("show");modal.innerHTML=""}
backdrop.addEventListener("click",e=>{if(e.target===backdrop)closeModal()});

function getInitials(name){return (name||"U").trim().split(/\s+/).slice(0,2).map(x=>x[0]).join("").toUpperCase()}
function setupUserUI(){
 const name=session?.name||"User", initials=getInitials(name);
 ["profileName","topUserName"].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=name});
 ["profileAvatar","topAvatar"].forEach(id=>{const el=document.getElementById(id);if(el)el.textContent=initials});
 const active=data.tasks.filter(t=>!t.done).length; const badge=document.getElementById("taskBadge");if(badge)badge.textContent=active;
}
function showAuth(){document.getElementById("authScreen").classList.remove("hidden");document.getElementById("appScreen").classList.add("hidden")}
function showApp(){document.getElementById("authScreen").classList.add("hidden");document.getElementById("appScreen").classList.remove("hidden");setupUserUI();loadTheme();showView(location.hash.slice(1)||"dashboard",false)}
function login(e){
 e.preventDefault();
 const email=document.getElementById("loginEmail").value.trim().toLowerCase(), pass=document.getElementById("loginPassword").value;
 if(!email||pass.length<6)return notify("Enter a valid email and 6+ character password");
 const users=JSON.parse(localStorage.getItem("aiLifeAdminUsers")||"{}");
 if(users[email] && users[email].password!==pass)return notify("Incorrect password");
 session=users[email]||{name:email.split("@")[0],email};
 localStorage.setItem(SESSION,JSON.stringify(session));load();showApp();notify("Welcome to your workspace")}
function signup(e){
 e.preventDefault();
 const name=document.getElementById("signupName").value.trim(),email=document.getElementById("signupEmail").value.trim().toLowerCase(),pass=document.getElementById("signupPassword").value;
 if(!name||!email||pass.length<6)return notify("Complete all fields; password needs 6+ characters");
 const users=JSON.parse(localStorage.getItem("aiLifeAdminUsers")||"{}");
 if(users[email])return notify("An account with this email already exists");
 users[email]={name,email,password:pass};localStorage.setItem("aiLifeAdminUsers",JSON.stringify(users));
 session=users[email];localStorage.setItem(SESSION,JSON.stringify(session));data=emptyData();save();showApp();notify("Account created — your workspace is empty and ready")}
function logout(){localStorage.removeItem(SESSION);session=null;data=emptyData();location.hash="";showAuth();notify("Logged out")}
window.login=login;window.signup=signup;window.logout=logout;

document.querySelectorAll(".auth-tab").forEach(btn=>btn.addEventListener("click",()=>{
 document.querySelectorAll(".auth-tab").forEach(b=>b.classList.remove("active"));btn.classList.add("active");
 document.getElementById("loginForm").classList.toggle("hidden",btn.dataset.auth!=="login");
 document.getElementById("signupForm").classList.toggle("hidden",btn.dataset.auth!=="signup");
}));

function layoutHead(ey,h1,desc,actions=""){return `<div class="page-head"><div><div class="eyebrow">${ey}</div><h1>${h1}</h1><p>${desc}</p></div><div class="head-actions">${actions}</div></div>`}
function stat(icon,label,value,trend,cls){return `<div class="stat-card"><div class="stat-top"><span>${label}</span><span class="stat-icon ${cls}">${icon}</span></div><div class="stat-value">${value}</div><div class="trend">${trend}</div></div>`}
function taskHTML(t,i){return `<div class="task"><button class="check ${t.done?"done":""}" onclick="toggleTask('${t.id}')">${t.done?"✓":""}</button><div><strong style="${t.done?"text-decoration:line-through;color:#98a1b2":""}">${esc(t.title)}</strong><small>${esc(t.client||"Personal")} • ${esc(t.due||"No due date")} • ${esc(t.category||"General")}</small></div><span class="priority ${(t.priority||"Medium").toLowerCase()}">${esc(t.priority||"Medium")}</span></div>`}

function dashboard(){
 const active=data.tasks.filter(t=>!t.done).length, income=data.income.reduce((s,x)=>s+Number(x.amount||0),0), expenses=data.expenses.reduce((s,x)=>s+Number(x.amount||0),0), balance=income-expenses;
 return layoutHead("Command center",`Welcome, ${esc(session.name)} 👋`,"A clean workspace for your personal life and client work.",`<button class="btn" onclick="showView('assistant')">✦ AI Assistant</button><button class="btn primary" onclick="addTask()">＋ Add task</button>`) +
 `<div class="grid stats">${stat("✓","Active tasks",active,"Your current workload","violet")}${stat("₹","Balance","₹"+balance.toLocaleString("en-IN"),"Tracked income minus expenses","orange")}${stat("♡","Health logged",data.health.water||0,"Water glasses today","green")}${stat("↻","Habit streaks",data.habits.length,"Habits in your routine","cyan")}</div>
 <div class="grid two-col">
  <div class="card"><div class="card-head"><div><h3>My tasks</h3><p>${data.tasks.length?active+" active tasks":"Your task list is empty"}</p></div><button class="link-btn" onclick="showView('tasks')">Open →</button></div><div class="card-body">${data.tasks.length?data.tasks.slice(0,5).map(taskHTML).join(""):`<div class="empty">No tasks yet.<br><button class="btn primary" style="margin-top:10px" onclick="addTask()">＋ Add your first task</button></div>`}</div></div>
  <div class="card"><div class="card-head"><div><h3>Quick modules</h3><p>Jump directly to what you need</p></div></div><div class="card-body">${[
   ["₹","Finance & Expenses","Track income, spending and budgets","finance"],
   ["♡","Health","Log wellness and reminders","health"],
   ["↻","Routine & Habits","Build consistent daily habits","routine"],
   ["▣","Calendar","Manage your events and deadlines","calendar"]
  ].map(x=>`<button class="task" style="width:100%;border:0;background:none;text-align:left" onclick="showView('${x[3]}')"><span>${x[0]}</span><div><strong>${x[1]}</strong><small>${x[2]}</small></div><span>→</span></button>`).join("")}</div></div>
 </div>
 <div class="ai-banner"><div><h3>✦ AI-ready workspace</h3><p>Your frontend is now clean and user-driven. In the backend phase, tasks, clients, finance, health and habits will be saved per account and the AI API will be connected securely.</p></div><button class="ai-pill" onclick="showView('assistant')">Open AI Assistant →</button></div>`;
}

function assistant(){return layoutHead("AI Copilot","AI Life Assistant","Ask for a plan, prioritize work, summarize notes or review your spending.",`<button class="btn" onclick="notify('AI voice will be connected in the AI phase')">🎙 Voice</button>`) +
 `<div class="assistant"><div class="card"><div class="card-head"><div><h3>Life Assistant</h3><p>Prototype chat — AI API comes later</p></div><span class="tag">Ready</span></div><div class="messages" id="messages"><div class="bubble ai">Hi ${esc(session.name)}. Your workspace is empty by design. Tell me what you want to organize.</div></div><div class="quick-prompts"><button onclick="quickPrompt('Plan my day')">Plan my day</button><button onclick="quickPrompt('Prioritize my tasks')">Prioritize tasks</button><button onclick="quickPrompt('Review my expenses')">Review expenses</button><button onclick="quickPrompt('Create a habit routine')">Create routine</button></div><form class="chat-input" id="chatForm"><input id="chatInput" placeholder="Ask your assistant..."><button class="btn primary">Send</button></form></div>
 <div class="card"><div class="card-head"><h3>AI capabilities planned</h3></div><div class="card-body">${["Natural-language task creation","Smart scheduling","Client task prioritization","Expense insights","Habit planning","Weekly executive summary"].map(x=>`<div class="task"><span style="color:#655bea">✦</span><div><strong>${x}</strong><small>Backend + AI integration</small></div></div>`).join("")}</div></div></div>`}

function tasks(){
 const clients=[...new Set(data.tasks.map(t=>t.client).filter(Boolean))];
 return layoutHead("Work management","Tasks & Client Work","Add tasks for yourself or a client. Nothing is pre-filled.",`<button class="btn" onclick="openTaskFilter()">⌕ Filter</button><button class="btn primary" onclick="addTask()">＋ Add task</button>`) +
 `<div class="card"><div class="card-head"><div><h3>Task list</h3><p>${data.tasks.filter(t=>!t.done).length} active • ${data.tasks.filter(t=>t.done).length} completed${clients.length?" • "+clients.length+" clients":""}</p></div></div><div class="card-body" id="taskList">${data.tasks.length?data.tasks.map(taskHTML).join(""):`<div class="empty">No tasks yet. Add your first personal or client task.</div>`}</div></div>`}

function calendar(){return layoutHead("Planning","Calendar","Add your own events and deadlines. The calendar starts empty.",`<button class="btn primary" onclick="addEvent()">＋ Add event</button>`)+
`<div class="card"><div class="card-head"><div><h3>October 2026</h3><p>Your saved events appear here.</p></div></div><div class="card-body"><div class="calendar">${["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=>`<div class="day-head">${d}</div>`).join("")}${Array.from({length:35},(_,i)=>{let n=i-3,ev=data.events.filter(e=>Number(e.date?.split("-")[2])===n);return `<div class="day ${n===new Date().getDate()?"today":""} ${n<1||n>31?"muted-day":""}">${n<1||n>31?"":n}${ev.map(e=>`<div class="event">${esc(e.title)}</div>`).join("")}</div>`}).join("")}</div></div></div>`}

function notes(){return layoutHead("Knowledge","Notes","Your private notes. Start with a blank workspace.",`<button class="btn primary" onclick="addNote()">＋ New note</button>`)+`<div class="grid three-col">${data.notes.length?data.notes.map(n=>`<div class="card"><div class="card-body"><span class="tag">${esc(n.tag||"Personal")}</span><h3 style="margin:12px 0 7px">${esc(n.title)}</h3><p class="muted" style="line-height:1.7;font-size:9px">${esc(n.text)}</p></div></div>`).join(""):`<div class="card" style="grid-column:1/-1"><div class="card-body empty">No notes yet. Create your first note.</div></div>`}</div>`}

function goals(){return layoutHead("Growth","Goals","Create goals and track progress.",`<button class="btn primary" onclick="addGoal()">＋ Add goal</button>`)+`<div class="grid three-col">${data.goals.length?data.goals.map(g=>`<div class="card"><div class="card-body"><div class="goal-title"><strong>${esc(g.title)}</strong><b>${g.progress}%</b></div><div class="progress"><i style="width:${g.progress}%"></i></div><small class="muted">${esc(g.meta||"New goal")}</small></div></div>`).join(""):`<div class="card" style="grid-column:1/-1"><div class="card-body empty">No goals yet. Add your first goal.</div></div>`}</div>`}

function routine(){return layoutHead("Consistency","Routine & Habit Tracker","Build routines and maintain streaks.",`<button class="btn primary" onclick="addHabit()">＋ Add habit</button>`)+`<div class="routine-grid">${data.habits.length?data.habits.map((h,i)=>`<div class="card"><div class="card-body"><div class="goal-title"><strong>${esc(h.name)}</strong><b>${h.streak||0} days</b></div><p class="muted" style="font-size:9px;margin-top:7px">${h.done?"Completed today":"Not completed today"}</p><div class="habit-day">${Array.from({length:7},(_,d)=>`<span class="${d<Math.min(7,h.streak||0)?"done":""}"></span>`).join("")}</div><button class="btn small" style="margin-top:15px" onclick="toggleHabit('${h.id}')">${h.done?"Mark incomplete":"Complete today"}</button></div></div>`).join(""):`<div class="card" style="grid-column:1/-1"><div class="card-body empty">No habits yet. Add your first routine.</div></div>`}</div>`}

function health(){const h=data.health;return layoutHead("Wellness","Health Dashboard","A private wellness organizer. This is not medical advice.",`<button class="btn primary" onclick="addHealthEntry()">＋ Log health</button>`)+
`<div class="health-grid"><div class="health-stat"><span class="muted">💧 Water</span><div class="metric-big">${h.water}/${h.waterTarget}</div><small class="muted">glasses today</small><div class="progress"><i style="width:${Math.min(100,h.water/h.waterTarget*100)}%"></i></div></div><div class="health-stat"><span class="muted">🌙 Sleep</span><div class="metric-big">${h.sleep||0}h</div><small class="muted">target ${h.sleepTarget}h</small><div class="progress"><i style="width:${Math.min(100,(h.sleep||0)/h.sleepTarget*100)}%"></i></div></div><div class="health-stat"><span class="muted">🚶 Steps</span><div class="metric-big">${Number(h.steps||0).toLocaleString()}</div><small class="muted">target ${h.stepTarget.toLocaleString()}</small><div class="progress"><i style="width:${Math.min(100,(h.steps||0)/h.stepTarget*100)}%"></i></div></div></div>
<div class="grid two-col" style="margin-top:16px"><div class="card"><div class="card-head"><h3>Today's check-in</h3><span class="tag">${esc(h.mood)}</span></div><div class="card-body"><div class="metric-row"><div class="metric"><b>${h.water}</b><span>Water</span></div><div class="metric"><b>${h.sleep||0}h</b><span>Sleep</span></div><div class="metric"><b>${h.appointments}</b><span>Appointments</span></div></div></div></div><div class="card"><div class="card-head"><h3>Health reminders</h3></div><div class="card-body"><div class="empty">${h.appointments?"You have "+h.appointments+" saved appointment(s).":"No health reminders yet."}</div></div></div></div>`}

function finance(){const income=data.income.reduce((s,x)=>s+Number(x.amount||0),0),expense=data.expenses.reduce((s,x)=>s+Number(x.amount||0),0),bal=income-expense;return layoutHead("Money","Finance & Expense Tracker","Track your own income and spending. Starts empty.",`<button class="btn primary" onclick="addExpense()">＋ Add expense</button><button class="btn" onclick="addIncome()">＋ Add income</button>`)+
`<div class="grid stats">${stat("₹","Income","₹"+income.toLocaleString("en-IN"),"Tracked income","green")}${stat("↘","Expenses","₹"+expense.toLocaleString("en-IN"),"Tracked spending","orange")}${stat("✓","Balance","₹"+bal.toLocaleString("en-IN"),"Income minus expenses","violet")}${stat("%","Savings rate",income?Math.round(bal/income*100)+"%":"0%","Based on tracked data","cyan")}</div><div class="grid two-col" style="margin-top:16px"><div class="card"><div class="card-head"><h3>Recent expenses</h3></div><div class="card-body">${data.expenses.length?data.expenses.map((e,i)=>`<div class="expense-row"><div><strong>${esc(e.name)}</strong><div class="muted" style="font-size:8px">${esc(e.category)} • ${esc(e.date||"")}</div></div><span>− ₹${Number(e.amount).toLocaleString("en-IN")}</span><button class="link-btn" onclick="deleteExpense('${e.id}')">Remove</button></div>`).join(""):`<div class="empty">No expenses yet.</div>`}</div></div><div class="card"><div class="card-head"><h3>Income</h3></div><div class="card-body">${data.income.length?data.income.map(x=>`<div class="task"><div><strong>${esc(x.name)}</strong><small>${esc(x.date||"")}</small></div><b>₹${Number(x.amount).toLocaleString("en-IN")}</b></div>`).join(""):`<div class="empty">No income records yet.</div>`}</div></div></div>`}

function bills(){return layoutHead("Money","Bills & Payments","Track recurring and one-time payments.",`<button class="btn primary" onclick="addBill()">＋ Add payment</button>`)+`<div class="card"><div class="card-body table-wrap">${data.bills.length?`<table class="data-table"><thead><tr><th>Payment</th><th>Amount</th><th>Due</th><th>Status</th></tr></thead><tbody>${data.bills.map(b=>`<tr><td>${esc(b.name)}</td><td>${esc(b.amount)}</td><td>${esc(b.due||"")}</td><td><span class="tag">${esc(b.status||"Upcoming")}</span></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No bills yet.</div>`}</div></div>`}

function documents(){return layoutHead("Vault","Documents","Store document metadata now; secure file storage will be connected to the backend.",`<button class="btn primary" onclick="uploadDoc()">＋ Add document</button>`)+`<div class="card"><div class="card-body table-wrap">${data.documents.length?`<table class="data-table"><thead><tr><th>Document</th><th>Category</th><th>Expiry</th><th>Status</th></tr></thead><tbody>${data.documents.map(d=>`<tr><td>${esc(d.name)}</td><td>${esc(d.type)}</td><td>${esc(d.expiry||"—")}</td><td><span class="tag">${esc(d.status||"Active")}</span></td></tr>`).join("")}</tbody></table>`:`<div class="empty">No documents yet.</div>`}</div></div>`}

function analytics(){const completed=data.tasks.filter(t=>t.done).length;return layoutHead("Insights","Executive Analytics","Your analytics become meaningful as you add real data.",`<button class="btn" onclick="notify('Report export will be connected to the backend')">↓ Export</button>`)+`<div class="grid stats">${stat("✓","Completed tasks",completed,"From your workspace","green")}${stat("₹","Expenses","₹"+data.expenses.reduce((s,x)=>s+Number(x.amount||0),0).toLocaleString("en-IN"),"Tracked","orange")}${stat("◎","Goals",data.goals.length,"Created","cyan")}${stat("↻","Habits",data.habits.length,"Created","violet")}</div><div class="card" style="margin-top:16px"><div class="card-body empty">Add tasks, expenses, goals and habits to unlock richer analytics.</div></div>`}

function settings(){const theme=localStorage.getItem(THEME)||"light";return layoutHead("Preferences","Settings","Update your profile and choose your executive theme.")+
`<div class="grid two-col"><div class="card"><div class="card-head"><h3>Profile</h3></div><div class="card-body"><div class="form-grid"><div class="field"><label>Name</label><input id="profileInput" value="${esc(session.name)}"></div><div class="field"><label>Email</label><input value="${esc(session.email)}" disabled></div></div><button class="btn primary" style="margin-top:15px" onclick="saveProfile()">Save profile</button></div></div><div class="card"><div class="card-head"><div><h3>Theme</h3><p>Light, dark or premium glassmorphic executive style.</p></div></div><div class="card-body"><div class="theme-options"><button class="theme-option ${theme==="light"?"active":""}" onclick="setTheme('light')"><strong>☀ Light</strong><small>Clean & bright</small></button><button class="theme-option ${theme==="dark"?"active":""}" onclick="setTheme('dark')"><strong>☾ Dark</strong><small>Focused & low-glare</small></button><button class="theme-option ${theme==="glass"?"active":""}" onclick="setTheme('glass')"><strong>◈ Glass Executive</strong><small>Premium glassmorphism</small></button></div></div></div></div>`}

const views={dashboard,assistant,tasks,calendar,notes,goals,routine,health,finance,bills,documents,analytics,settings};
function showView(view,history=true){if(!views[view])view="dashboard";app.innerHTML=views[view]();title.textContent=view.replace(/(^|\\s)\\S/g,m=>m.toUpperCase());document.querySelectorAll(".nav-link[data-view]").forEach(a=>a.classList.toggle("active",a.dataset.view===view));setupUserUI();if(innerWidth<760)document.getElementById("sidebar").classList.remove("open");if(history){const url=view==="dashboard"?location.pathname:location.pathname+"#"+view;window.history.pushState({view},"",url)}if(view==="assistant")bindChat();window.scrollTo({top:0,behavior:"smooth"})}
window.showView=showView;
window.addEventListener("popstate",()=>showView(location.hash.slice(1)||"dashboard",false));

function persistTask(t){data.tasks.push(t);save();setupUserUI();notify("Task added to your workspace");showView("tasks")}
function addTask(){openModal(`<div class="modal-head"><h3>Add task</h3><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field full"><label>Task title</label><input id="taskTitle" placeholder="What needs to be done?" autofocus></div><div class="field"><label>For</label><select id="taskOwner"><option value="Personal">Myself</option><option value="Client">Client</option></select></div><div class="field"><label>Client / user name</label><input id="taskClient" placeholder="Optional"></div><div class="field"><label>Priority</label><select id="taskPriority"><option>High</option><option selected>Medium</option><option>Low</option></select></div><div class="field"><label>Due date</label><input id="taskDue" type="date"></div><div class="field"><label>Category</label><select id="taskCategory"><option>Personal</option><option>Work</option><option>College</option><option>Career</option><option>Finance</option><option>Health</option><option>Other</option></select></div><div class="field"><label>Status</label><select id="taskStatus"><option value="false">Pending</option><option value="true">Completed</option></select></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveTask()">Add task</button></div>`)}
function saveTask(){const title=document.getElementById("taskTitle").value.trim();if(!title)return notify("Enter a task title");const owner=document.getElementById("taskOwner").value,client=document.getElementById("taskClient").value.trim()|| (owner==="Client"?"Unnamed client":"Personal");persistTask({id:uid(),title,owner,client,priority:document.getElementById("taskPriority").value,due:document.getElementById("taskDue").value||"No due date",category:document.getElementById("taskCategory").value,done:document.getElementById("taskStatus").value==="true"})}
function toggleTask(id){const t=data.tasks.find(x=>x.id===id);if(t){t.done=!t.done;save();setupUserUI();showView("tasks",false);notify(t.done?"Task completed ✓":"Task reopened")}}
function openTaskFilter(){openModal(`<div class="modal-head"><h3>Task filter</h3><button class="close" onclick="closeModal()">×</button></div><div class="field"><label>Client / user</label><input id="filterClient" placeholder="Search client"></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="filterTasks()">Apply</button></div>`)}
function filterTasks(){const q=document.getElementById("filterClient").value.trim().toLowerCase();closeModal();const box=document.getElementById("taskList");const arr=q?data.tasks.filter(t=>(t.client||"").toLowerCase().includes(q)):data.tasks;box.innerHTML=arr.length?arr.map(taskHTML).join(""):`<div class="empty">No matching tasks.</div>`}

function addEvent(){openModal(`<div class="modal-head"><h3>Add calendar event</h3><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field full"><label>Event title</label><input id="eventTitle" placeholder="Meeting, deadline, appointment..."></div><div class="field"><label>Date</label><input id="eventDate" type="date"></div><div class="field"><label>Time</label><input id="eventTime" type="time"></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveEvent()">Add event</button></div>`)}
function saveEvent(){const title=document.getElementById("eventTitle").value.trim();if(!title)return notify("Enter an event title");data.events.push({id:uid(),title,date:document.getElementById("eventDate").value,time:document.getElementById("eventTime").value});save();closeModal();showView("calendar");notify("Event added")}
function addNote(){openModal(`<div class="modal-head"><h3>New note</h3><button class="close" onclick="closeModal()">×</button></div><div class="field"><label>Title</label><input id="noteTitle"></div><div class="field" style="margin-top:12px"><label>Content</label><textarea id="noteText"></textarea></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveNote()">Save</button></div>`)}
function saveNote(){const title=document.getElementById("noteTitle").value.trim(),text=document.getElementById("noteText").value.trim();if(!title||!text)return notify("Add title and content");data.notes.push({id:uid(),title,text,tag:"Personal"});save();closeModal();showView("notes");notify("Note saved")}
function addGoal(){openModal(`<div class="modal-head"><h3>Add goal</h3><button class="close" onclick="closeModal()">×</button></div><div class="field"><label>Goal name</label><input id="goalTitle" placeholder="e.g. Complete portfolio"></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveGoal()">Create</button></div>`)}
function saveGoal(){const title=document.getElementById("goalTitle").value.trim();if(!title)return notify("Enter a goal");data.goals.push({id:uid(),title,progress:0,meta:"New goal"});save();closeModal();showView("goals");notify("Goal created")}
function addHabit(){openModal(`<div class="modal-head"><h3>Add habit</h3><button class="close" onclick="closeModal()">×</button></div><div class="field"><label>Habit name</label><input id="habitName" placeholder="e.g. 30 min coding"></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveHabit()">Add habit</button></div>`)}
function saveHabit(){const name=document.getElementById("habitName").value.trim();if(!name)return notify("Enter a habit");data.habits.push({id:uid(),name,streak:0,done:false});save();closeModal();showView("routine");notify("Habit added")}
function toggleHabit(id){const h=data.habits.find(x=>x.id===id);if(h){h.done=!h.done;if(h.done)h.streak++;save();showView("routine",false);notify(h.done?"Habit completed ✓":"Habit reopened")}}
function addHealthEntry(){openModal(`<div class="modal-head"><h3>Log health</h3><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field"><label>Water glasses</label><input id="hWater" type="number" min="0" value="${data.health.water}"></div><div class="field"><label>Sleep hours</label><input id="hSleep" type="number" min="0" step=".1" value="${data.health.sleep}"></div><div class="field"><label>Steps</label><input id="hSteps" type="number" min="0" value="${data.health.steps}"></div><div class="field"><label>Mood</label><select id="hMood"><option>Good</option><option>Okay</option><option>Low</option></select></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveHealth()">Save</button></div>`)}
function saveHealth(){data.health.water=Number(document.getElementById("hWater").value)||0;data.health.sleep=Number(document.getElementById("hSleep").value)||0;data.health.steps=Number(document.getElementById("hSteps").value)||0;data.health.mood=document.getElementById("hMood").value;save();closeModal();showView("health");notify("Health data saved")}
function addExpense(){openModal(`<div class="modal-head"><h3>Add expense</h3><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field full"><label>Name</label><input id="eName" placeholder="e.g. Travel"></div><div class="field"><label>Amount (₹)</label><input id="eAmount" type="number" min="0"></div><div class="field"><label>Category</label><select id="eCat"><option>Food</option><option>Transport</option><option>Education</option><option>Bills</option><option>Housing</option><option>Shopping</option><option>Other</option></select></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveExpense()">Add</button></div>`)}
function saveExpense(){const name=document.getElementById("eName").value.trim(),amount=Number(document.getElementById("eAmount").value);if(!name||!amount)return notify("Enter name and amount");data.expenses.push({id:uid(),name,amount,category:document.getElementById("eCat").value,date:new Date().toLocaleDateString("en-IN")});save();closeModal();showView("finance");notify("Expense added")}
function deleteExpense(id){data.expenses=data.expenses.filter(x=>x.id!==id);save();showView("finance",false);notify("Expense removed")}
function addIncome(){openModal(`<div class="modal-head"><h3>Add income</h3><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field"><label>Source</label><input id="iName" placeholder="Salary / freelance"></div><div class="field"><label>Amount (₹)</label><input id="iAmount" type="number" min="0"></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveIncome()">Add</button></div>`)}
function saveIncome(){const name=document.getElementById("iName").value.trim(),amount=Number(document.getElementById("iAmount").value);if(!name||!amount)return notify("Enter source and amount");data.income.push({id:uid(),name,amount,date:new Date().toLocaleDateString("en-IN")});save();closeModal();showView("finance");notify("Income added")}
function addBill(){openModal(`<div class="modal-head"><h3>Add payment</h3><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field"><label>Name</label><input id="bName"></div><div class="field"><label>Amount</label><input id="bAmount"></div><div class="field"><label>Due date</label><input id="bDue" type="date"></div><div class="field"><label>Status</label><select id="bStatus"><option>Upcoming</option><option>Paid</option><option>Scheduled</option></select></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveBill()">Add</button></div>`)}
function saveBill(){const name=document.getElementById("bName").value.trim(),amount=document.getElementById("bAmount").value.trim();if(!name||!amount)return notify("Enter payment name and amount");data.bills.push({id:uid(),name,amount,due:document.getElementById("bDue").value||"—",status:document.getElementById("bStatus").value});save();closeModal();showView("bills");notify("Payment added")}
function uploadDoc(){openModal(`<div class="modal-head"><h3>Add document</h3><button class="close" onclick="closeModal()">×</button></div><div class="form-grid"><div class="field full"><label>Document name</label><input id="dName" placeholder="Resume.pdf"></div><div class="field"><label>Category</label><select id="dType"><option>Personal</option><option>Career</option><option>Education</option><option>Finance</option><option>Other</option></select></div><div class="field"><label>Expiry</label><input id="dExpiry" type="date"></div></div><div class="modal-actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveDoc()">Add</button></div>`)}
function saveDoc(){const name=document.getElementById("dName").value.trim();if(!name)return notify("Enter a document name");data.documents.push({id:uid(),name,type:document.getElementById("dType").value,expiry:document.getElementById("dExpiry").value||"—",status:"Active"});save();closeModal();showView("documents");notify("Document added")}
function saveProfile(){const name=document.getElementById("profileInput").value.trim();if(!name)return notify("Enter your name");session.name=name;localStorage.setItem(SESSION,JSON.stringify(session));const users=JSON.parse(localStorage.getItem("aiLifeAdminUsers")||"{}");if(users[session.email]){users[session.email].name=name;localStorage.setItem("aiLifeAdminUsers",JSON.stringify(users))}setupUserUI();notify("Profile updated")}
function setTheme(theme){localStorage.setItem(THEME,theme);applyTheme();showView("settings",false);notify("Theme updated")}
function applyTheme(){const theme=localStorage.getItem(THEME)||"light";document.body.classList.remove("theme-dark","theme-glass");if(theme==="dark")document.body.classList.add("theme-dark");if(theme==="glass")document.body.classList.add("theme-glass")}
function openSearch(){openModal(`<div class="modal-head"><h3>Global search</h3><button class="close" onclick="closeModal()">×</button></div><div class="search-box"><input id="searchInput" placeholder="Search your data"><button class="btn primary" onclick="runSearch()">Search</button></div><div id="searchResults"></div>`)}
function runSearch(){const q=document.getElementById("searchInput").value.trim().toLowerCase();const all=[...data.tasks.map(x=>["Task",x.title]),...data.notes.map(x=>["Note",x.title]),...data.goals.map(x=>["Goal",x.title]),...data.expenses.map(x=>["Expense",x.name]),...data.documents.map(x=>["Document",x.name])];const r=all.filter(x=>x[1].toLowerCase().includes(q));document.getElementById("searchResults").innerHTML=r.length?r.map(x=>`<div class="result"><b>${x[0]}</b> · ${esc(x[1])}</div>`).join(""):`<div class="empty">No results.</div>`}
function quickPrompt(text){const input=document.getElementById("chatInput");input.value=text;document.getElementById("chatForm").dispatchEvent(new Event("submit"))}
function bindChat(){const form=document.getElementById("chatForm");if(!form)return;form.onsubmit=e=>{e.preventDefault();const input=document.getElementById("chatInput"),q=input.value.trim();if(!q)return;const box=document.getElementById("messages");box.insertAdjacentHTML("beforeend",`<div class="bubble user">${esc(q)}</div>`);input.value="";setTimeout(()=>{let r="I’m ready to turn that into actions. The real AI model will be connected securely through the backend in a later phase.";if(/task|work/i.test(q))r=`You currently have ${data.tasks.filter(t=>!t.done).length} active task(s). Use Add task to create one for yourself or a client.`;if(/expense|money|finance/i.test(q))r=`You have tracked ₹${data.expenses.reduce((s,x)=>s+Number(x.amount||0),0).toLocaleString("en-IN")} in expenses.`;if(/habit|routine/i.test(q))r=`You have ${data.habits.length} habit(s). Add routines from Routine & Habits.`;box.insertAdjacentHTML("beforeend",`<div class="bubble ai">${r}</div>`);box.scrollTop=box.scrollHeight},350)}}
document.getElementById("mobileMenu").onclick=()=>document.getElementById("sidebar").classList.toggle("open");

Object.assign(window,{addTask,saveTask,toggleTask,openTaskFilter,filterTasks,addEvent,saveEvent,addNote,saveNote,addGoal,saveGoal,addHabit,saveHabit,toggleHabit,addHealthEntry,saveHealth,addExpense,saveExpense,deleteExpense,addIncome,saveIncome,addBill,saveBill,uploadDoc,saveDoc,saveProfile,setTheme,openSearch,runSearch,quickPrompt,closeModal,showView});

applyTheme();
const savedSession=localStorage.getItem(SESSION);
if(savedSession){try{session=JSON.parse(savedSession);load();showApp()}catch{showAuth()}}else showAuth();
